### ISSUE TITLE
what is the PyTorch version of this project?

### ISSUE THREAD

**Issue by vegetable-most** [Zui-C/RLFN#1]
Hello! could you please show us the requirement of the related packages?

**Comment by Zui-C** [comment]
Hi,
I just export and upload my Conda env list, you can refer to it.

**Comment by Zui-C** [comment]
> Hello! could you please show us the requirement of the related packages?

Hi,
I just export and upload my Conda env list, you can refer to it.

**Comment by vegetable-most** [comment]
Thank you very much!
