### ISSUE TITLE
训练遇到的问题

### ISSUE THREAD

**Issue by SuperHHzy** [Zui-C/RLFN#2]
![image](https://github.com/Zui-C/RLFN/assets/107484371/4bc33202-e4bb-45af-9713-5ae0b416b052)
请问这个问题怎么解决啊？

**Comment by Zui-C** [comment]
您好，没有遇到这样的问题。
从你的traceback看，个人建议你先检测language_encoder是否能够正常编码。
单独载入你的language_encoder，输入一段序列，检查输出维度。

**Comment by Zui-C** [comment]
> ![image](https://private-user-images.githubusercontent.com/107484371/328431559-4bc33202-e4bb-45af-9713-5ae0b416b052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjgzMjgsIm5iZiI6MTcxNTA2ODAyOCwicGF0aCI6Ii8xMDc0ODQzNzEvMzI4NDMxNTU5LTRiYzMzMjAyLWU0YmItNDVhZi05NzEzLTVhZTBiNDE2YjA1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwNzQ3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTZhOGMzOTk3YzViZmIwZGQ2N2U1NjhiYzI0ODc5MWRlZTYxNWI0ZGJlODU4MmY2ODA4YjhmMDc2MjZkNzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SIdNo-pHnL2YUKNkuVhCsQ-Yeqd9ouprBaqzyDzhGHc) 请问这个问题怎么解决啊？

您好，没有遇到过这样的问题。
从你的traceback看，个人建议你先检测language_encoder是否能够正常编码。
单独载入你的language_encoder，输入一段序列，检查输出维度。

**Comment by SuperHHzy** [comment]
该项目提供的权重文件是否可用呢？我运行inference.py，提示我需要训练模型

**Comment by Zui-C** [comment]
> 该项目提供的权重文件是否可用呢？我运行inference.py，提示我需要训练模型

您好，readme中已说明未保存被冻结的语言编码器权重，检查你使用设备和hf的网络情况，如果不能自动下载，你可以考虑手动下载然后更改路径。对于推理中提示需要训练模型，可能理解有误，不应该存在这一情况。只有你在更换语言模型后需要重新训练融合模块。

**Comment by SuperHHzy** [comment]
![image](https://github.com/Zui-C/RLFN/assets/107484371/a6636d8d-0574-45a3-92df-37879d41ef04)
直接运行推理文件，有这样的报错。我之前手动下载了witiko/mathberta目录下的文件

**Comment by SuperHHzy** [comment]
![Uploading image.png…]()
这是witiko/mathberta目录下的文件

**Comment by Zui-C** [comment]
> ![image](https://private-user-images.githubusercontent.com/107484371/328446805-a6636d8d-0574-45a3-92df-37879d41ef04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzExMTksIm5iZiI6MTcxNTA3MDgxOSwicGF0aCI6Ii8xMDc0ODQzNzEvMzI4NDQ2ODA1LWE2NjM2ZDhkLTA1NzQtNDVhMy05MmRmLTM3ODc5ZDQxZWYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwODMzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjk1YjI1ZjU3Y2QzOGQ4NzgxMDU2Y2EyYjlkNGExMWY3NDY4ZjdjZGEwY2RiMjE5MTdkNTE3ZGJkZDcxZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zsgy-7JeglELhAB4X_iLmFmS5edJYc283lepzRIheFE) 直接运行推理文件，有这样的报错。我之前手动下载了witiko/mathberta目录下的文件

traceback的报错和提示需要训练来使用它们的语言模型无关。请你自行debug，来确定语言模型能被载入。我已经提供了建议 https://github.com/Zui-C/RLFN/issues/2#issuecomment-2097665058

**Comment by Zui-C** [comment]
> > ![image](https://private-user-images.githubusercontent.com/107484371/328446805-a6636d8d-0574-45a3-92df-37879d41ef04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzExMTksIm5iZiI6MTcxNTA3MDgxOSwicGF0aCI6Ii8xMDc0ODQzNzEvMzI4NDQ2ODA1LWE2NjM2ZDhkLTA1NzQtNDVhMy05MmRmLTM3ODc5ZDQxZWYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QwODMzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjk1YjI1ZjU3Y2QzOGQ4NzgxMDU2Y2EyYjlkNGExMWY3NDY4ZjdjZGEwY2RiMjE5MTdkNTE3ZGJkZDcxZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zsgy-7JeglELhAB4X_iLmFmS5edJYc283lepzRIheFE) 直接运行推理文件，有这样的报错。我之前手动下载了witiko/mathberta目录下的文件
> 
> traceback的报错和提示需要训练来使用它们的语言模型无关。请你自行debug，来确定语言模型能被载入。我已经提供了建议 [#2 (comment)](https://github.com/Zui-C/RLFN/issues/2#issuecomment-2097665058)

或者说直接尝试载入一下你下载的witiko/mathberta
