### ISSUE TITLE
I can not reproduce the result in the paper.

### ISSUE THREAD

**Issue by ducanh841988** [Zui-C/RLFN#3]
Thank you for your work. I try to re-run the experiment from your repo. 
I got an accuracy of ~49.XX from RLFN and it is a bit lower than WAP model only.
Do we need to change the config to reproduce the result in paper?
cc: @Zui-C

**Comment by Zui-C** [comment]
> Thank you for your work. I try to re-run the experiment from your repo. I got an accuracy of ~49.XX from RLFN and it is a bit lower than WAP model only. Do we need to change the config to reproduce the result in paper? cc: @Zui-C

Hi,
The uploaded configuration is the configuration used when training to obtain weights.
The weight best_thin do not save language part weight,  re-download it from hf to infer.
If not, it's like a DWAP.
