### ISSUE TITLE
Checkpoint broken

### ISSUE THREAD

**Issue by StephenLee369** [Zui-C/RLFN#4]
It seems that your checkpoint file has broken.Could you please offer a new one?
I tried to load the best_thin.pth in the same pytorch version as you offered in the requirements.txt, but it still reported the following bug:
```
模型加载失败： PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by Zui-C** [comment]
> It seems that your checkpoint file has broken.Could you please offer a new one? I tried to load the best_thin.pth in the same pytorch version as you offered in the requirements.txt, but it still reported the following bug:
> 
> ```
> 模型加载失败： PytorchStreamReader failed reading zip archive: failed finding central directory
> ```

The language model weights are frozen, and the final weight file separates this part, so it is called 'thin', which can be easily uploaded. You can download the language model weights from HF by yourself

**Comment by Zui-C** [comment]
> It seems that your checkpoint file has broken.Could you please offer a new one? I tried to load the best_thin.pth in the same pytorch version as you offered in the requirements.txt, but it still reported the following bug:
> 
> ```
> 模型加载失败： PytorchStreamReader failed reading zip archive: failed finding central directory
> ```

我看到你邮件中提供的载入代码。 请要么从RLFN的网络结构实例化一个，要么直接载入查看权重。

```

import torch

# 加载权重文件
model_weights = torch.load('path_to_your_file.pth')

# 打印所有键及其对应的张量形状
for key, value in model_weights.items():
    print(f"{key}: {value.shape}")

```

**Comment by StephenLee369** [comment]
Thank you for your reply. When I followed your code to load the model, it still repeated the error:"RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory". 
And When I tried to run inference.py after I imported the model path, it just repeated this error.
